version: "3.2"
services:
  flask:
    container_name: metrics-flask
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - MAPBOX_ACCESS_TOKEN
  react:
    container_name: metrics-react
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    command: ["npm", "run", "install-start"]
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_METRICS_BASE_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
